### ISSUE TITLE
Compress all files in a folder

### ISSUE THREAD

**Issue by aaani** [jney/grunt-htmlcompressor#15]
How can I compress all files in a folder and store the compressed file in another folder with the same name using grunt-htmlcompressor? I couldn't find an answer in the documentation. Thanks!
Something like following doesn't seem to work and I am forced to manually specify all the files:

<pre>
htmlcompressor: {
    compile: {
        files: {
            src: ['<%= yeoman.app %>/templates/*.html'],
            dest: '<%= yeoman.app %>/templates_compressed/'
        },
        options: {
            type: 'html',
            preserveServerScript: true,
            removeIntertagSpaces: true
        },

    }
}
</pre>

**Comment by jney** [comment]
https://github.com/jney/grunt-htmlcompressor#inputoutput-files

**Comment by jney** [comment]
i didn't actually merge the commit, see my comment

**Comment by aaani** [comment]
I had already read this link before creating this issue. Could you please provide an example as I am new to using Gruntjs?

**Comment by jney** [comment]
here's the signature of the function `processName(file.src, html)` 

i haven't test it, but i guess something like this should work : 

```
function (src) {
  return 'templates_compressed/' + src.split('/').pop();
}
```
