### ISSUE TITLE
Comment compresser tous les fichiers d'un répertoire ?

### ISSUE THREAD

**Issue by AlbanMinassian** [jney/grunt-htmlcompressor#2]
Bonjour. 
Avez vous un exemple pour compresser _tous_ les fichiers d'un répertoire vers un autre répertoire OU dans le même répertoire (mais avec une extension `.htmlc` par exemple ) ?

Cordialement
Ami44

**Comment by jney** [comment]
Bonjour,

pour les fichiers en entrée vous pouvez mettre n'importe quoi compatible avec le format proposé par minimatch (https://github.com/isaacs/minimatch) voire même une fonction.
Pour les fichiers en sortie, si l'option `processName` est fournie, une fonction est utilisée pour formater le fichier en sortie. 

```
htmlcompressor: {
  compress: {
    src: 'src/html/**/*.html',
    options: {
      type: 'html',
      processName: function (inputPath, content) {
        return inputPath + 'c';
      },
      preserveServerScript: true
    }
  }
}
```

**Comment by AlbanMinassian** [comment]
Merci pour la réponse et cet exemple précis. 

**Bug** : si je teste la compression d'un répertoire contenant plusieurs fichiers html, **seul le premier** est compressé !

```
`        // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
        // htmlcompressor ( grunt-htmlcompressor )
        // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
        htmlcompressor: {
           tmp_www_app_views_templates: {
                src: 'tmp/www/app/views/templates/**/*.html',
                options: {
                    type: 'html',
                    processName: function (inputPath, content) {
                        return inputPath + 'c';
                    },
                    preserveServerScript: true
                }                   
            }
        },

```

Avez-vous le même soucis ?
Cordialement
Ami44

**Comment by jney** [comment]
Désolé de répondre si tard.
ça devrait être corrigé maintenant.

**Comment by AlbanMinassian** [comment]
Merci @jney, je confirme la correction.

Petit détail : `npm update grunt-htmlcompressor` n'installe pas la dernière version. j'ai du copier/coller le code source à la mano.

Cordialement
Ami44

**Comment by jney** [comment]
ça devrait être bon maintenant
