### ISSUE TITLE
Task not working with recent Grunt

### ISSUE THREAD

**Issue by rlopes** [jney/grunt-htmlcompressor#5]
Using Grunt 0.3.16 I get this error:

Running "htmlcompressor:compile" (htmlcompressor) task
<WARN> Helper "options" not found. Use --force to continue. </WARN>

**Comment by rlopes** [comment]
That line might be causing the issue:

``` javascript
var options = grunt.helper('options', this);
```

**Comment by jney** [comment]
it's weird. i can not reproduce the error.

```
jney@architect ~/s/g/test> grunt test
Running "test:tasks" (test) task
Testing htmlcompressor_test.js.OK
>> 2 assertions passed (57ms)

Done, without errors.
jney@architect ~/s/g/test> grunt --version
grunt v0.3.16
```

by changing the line from

```
var options = grunt.helper('options', this);
```

to

```
var options = this.options({});
```

does it solve the problem ?

**Comment by rlopes** [comment]
Thanks. I am going to try.

However, as a side note, it seems that Grunt is getting rid of helpers in version 0.4. I am also using grunt-contrib who got rid of all their helpers recently.

**Comment by jney** [comment]
thank you for that. i will update the plugin.

**Comment by jney** [comment]
should be ready for 0.4.0a
