### ISSUE TITLE
TypeError: Object #<Object> has no method 'options'

### ISSUE THREAD

**Issue by osmestad** [jney/grunt-htmlcompressor#8]
I'm not able to get the compressor running, I get the following error:
Running "htmlcompressor:compile" (htmlcompressor) task

TypeError: Object #<Object> has no method 'options'
    at Object.module.exports.str (..../node_modules/grunt-htmlcompressor/tasks/grunt-htmlcompressor.js:17:24)

My configuration was:

``` javascript
htmlcompressor: {
      compile: {
        files: {
          'build/index.html': 'build/index.html'
        },
        options: {
          type: 'html'
        }
      }
    }
```

Grunt version: 0.3.17 (also tried 0.3.15)
grunt-htmlcompressor version: 0.1.5 and I tried  0.1.4

**Comment by raarce** [comment]
I think I solved this problem when I updated to grunt version 0.4.
